Attribute VB_Name = "niDCPower"
Option Explicit

Private Const NIDCPOWER_ATTR_BASE = IVI_SPECIFIC_PUBLIC_ATTR_BASE
Private Const NIDCPOWER_ATTR_PRIVATE_BASE = IVI_SPECIFIC_PRIVATE_ATTR_BASE

Private Enum IviDCPwr_AttributeIDs
    IVIDCPWR_ATTR_CACHE = IVI_ATTR_CACHE
    IVIDCPWR_ATTR_RANGE_CHECK = IVI_ATTR_RANGE_CHECK
    IVIDCPWR_ATTR_QUERY_INSTRUMENT_STATUS = IVI_ATTR_QUERY_INSTRUMENT_STATUS
    IVIDCPWR_ATTR_RECORD_COERCIONS = IVI_ATTR_RECORD_COERCIONS
    IVIDCPWR_ATTR_SIMULATE = IVI_ATTR_SIMULATE
    IVIDCPWR_ATTR_INTERCHANGE_CHECK = IVI_ATTR_INTERCHANGE_CHECK
    IVIDCPWR_ATTR_SPY = IVI_ATTR_SPY
    IVIDCPWR_ATTR_USE_SPECIFIC_SIMULATION = IVI_ATTR_USE_SPECIFIC_SIMULATION
    IVIDCPWR_ATTR_GROUP_CAPABILITIES = IVI_ATTR_GROUP_CAPABILITIES
    IVIDCPWR_ATTR_FUNCTION_CAPABILITIES = IVI_ATTR_FUNCTION_CAPABILITIES
    IVIDCPWR_ATTR_CLASS_DRIVER_PREFIX = IVI_ATTR_CLASS_DRIVER_PREFIX
    IVIDCPWR_ATTR_CLASS_DRIVER_VENDOR = IVI_ATTR_CLASS_DRIVER_VENDOR
    IVIDCPWR_ATTR_CLASS_DRIVER_DESCRIPTION = IVI_ATTR_CLASS_DRIVER_DESCRIPTION
    IVIDCPWR_ATTR_CLASS_DRIVER_CLASS_SPEC_MAJOR_VERSION = IVI_ATTR_CLASS_DRIVER_CLASS_SPEC_MAJOR_VERSION
    IVIDCPWR_ATTR_CLASS_DRIVER_CLASS_SPEC_MINOR_VERSION = IVI_ATTR_CLASS_DRIVER_CLASS_SPEC_MINOR_VERSION
    IVIDCPWR_ATTR_SPECIFIC_DRIVER_PREFIX = IVI_ATTR_SPECIFIC_DRIVER_PREFIX
    IVIDCPWR_ATTR_SPECIFIC_DRIVER_LOCATOR = IVI_ATTR_SPECIFIC_DRIVER_LOCATOR
    IVIDCPWR_ATTR_IO_RESOURCE_DESCRIPTOR = IVI_ATTR_IO_RESOURCE_DESCRIPTOR
    IVIDCPWR_ATTR_LOGICAL_NAME = IVI_ATTR_LOGICAL_NAME
    IVIDCPWR_ATTR_SPECIFIC_DRIVER_VENDOR = IVI_ATTR_SPECIFIC_DRIVER_VENDOR
    IVIDCPWR_ATTR_SPECIFIC_DRIVER_DESCRIPTION = IVI_ATTR_SPECIFIC_DRIVER_DESCRIPTION
    IVIDCPWR_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MAJOR_VERSION = IVI_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MAJOR_VERSION
    IVIDCPWR_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MINOR_VERSION = IVI_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MINOR_VERSION
    IVIDCPWR_ATTR_INSTRUMENT_FIRMWARE_REVISION = IVI_ATTR_INSTRUMENT_FIRMWARE_REVISION
    IVIDCPWR_ATTR_INSTRUMENT_MANUFACTURER = IVI_ATTR_INSTRUMENT_MANUFACTURER
    IVIDCPWR_ATTR_INSTRUMENT_MODEL = IVI_ATTR_INSTRUMENT_MODEL
    IVIDCPWR_ATTR_SUPPORTED_INSTRUMENT_MODELS = IVI_ATTR_SUPPORTED_INSTRUMENT_MODELS
    IVIDCPWR_ATTR_CLASS_DRIVER_REVISION = IVI_ATTR_CLASS_DRIVER_REVISION
    IVIDCPWR_ATTR_SPECIFIC_DRIVER_REVISION = IVI_ATTR_SPECIFIC_DRIVER_REVISION
    IVIDCPWR_ATTR_DRIVER_SETUP = IVI_ATTR_DRIVER_SETUP
    IVIDCPWR_ATTR_CHANNEL_COUNT = IVI_ATTR_CHANNEL_COUNT
    IVIDCPWR_ATTR_VOLTAGE_LEVEL = (IVI_CLASS_PUBLIC_ATTR_BASE + 1)
    IVIDCPWR_ATTR_OVP_ENABLED = (IVI_CLASS_PUBLIC_ATTR_BASE + 2)
    IVIDCPWR_ATTR_OVP_LIMIT = (IVI_CLASS_PUBLIC_ATTR_BASE + 3)
    IVIDCPWR_ATTR_CURRENT_LIMIT_BEHAVIOR = (IVI_CLASS_PUBLIC_ATTR_BASE + 4)
    IVIDCPWR_ATTR_CURRENT_LIMIT = (IVI_CLASS_PUBLIC_ATTR_BASE + 5)
    IVIDCPWR_ATTR_OUTPUT_ENABLED = (IVI_CLASS_PUBLIC_ATTR_BASE + 6)
    IVIDCPWR_ATTR_TRIGGER_SOURCE = (IVI_CLASS_PUBLIC_ATTR_BASE + 101)
    IVIDCPWR_ATTR_TRIGGERED_CURRENT_LIMIT = (IVI_CLASS_PUBLIC_ATTR_BASE + 102)
    IVIDCPWR_ATTR_TRIGGERED_VOLTAGE_LEVEL = (IVI_CLASS_PUBLIC_ATTR_BASE + 103)
End Enum

' Attribute IDs
Public Enum niDCPower_AttributeIDs
    NIDCPOWER_ATTR_RANGE_CHECK = IVI_ATTR_RANGE_CHECK
    NIDCPOWER_ATTR_QUERY_INSTRUMENT_STATUS = IVI_ATTR_QUERY_INSTRUMENT_STATUS
    NIDCPOWER_ATTR_CACHE = IVI_ATTR_CACHE
    NIDCPOWER_ATTR_SIMULATE = IVI_ATTR_SIMULATE
    NIDCPOWER_ATTR_RECORD_COERCIONS = IVI_ATTR_RECORD_COERCIONS
    NIDCPOWER_ATTR_INTERCHANGE_CHECK = IVI_ATTR_INTERCHANGE_CHECK
    NIDCPOWER_ATTR_CHANNEL_COUNT = IVI_ATTR_CHANNEL_COUNT
    NIDCPOWER_ATTR_SPECIFIC_DRIVER_PREFIX = IVI_ATTR_SPECIFIC_DRIVER_PREFIX
    NIDCPOWER_ATTR_SUPPORTED_INSTRUMENT_MODELS = IVI_ATTR_SUPPORTED_INSTRUMENT_MODELS
    NIDCPOWER_ATTR_GROUP_CAPABILITIES = IVI_ATTR_GROUP_CAPABILITIES
    NIDCPOWER_ATTR_INSTRUMENT_MANUFACTURER = IVI_ATTR_INSTRUMENT_MANUFACTURER
    NIDCPOWER_ATTR_INSTRUMENT_MODEL = IVI_ATTR_INSTRUMENT_MODEL
    NIDCPOWER_ATTR_INSTRUMENT_FIRMWARE_REVISION = IVI_ATTR_INSTRUMENT_FIRMWARE_REVISION
    NIDCPOWER_ATTR_SPECIFIC_DRIVER_REVISION = IVI_ATTR_SPECIFIC_DRIVER_REVISION
    NIDCPOWER_ATTR_SPECIFIC_DRIVER_VENDOR = IVI_ATTR_SPECIFIC_DRIVER_VENDOR
    NIDCPOWER_ATTR_SPECIFIC_DRIVER_DESCRIPTION = IVI_ATTR_SPECIFIC_DRIVER_DESCRIPTION
    NIDCPOWER_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MAJOR_VERSION = IVI_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MAJOR_VERSION
    NIDCPOWER_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MINOR_VERSION = IVI_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MINOR_VERSION
    NIDCPOWER_ATTR_SERIAL_NUMBER = NIDCPOWER_ATTR_BASE + 152
    NIDCPOWER_ATTR_LOGICAL_NAME = IVI_ATTR_LOGICAL_NAME
    NIDCPOWER_ATTR_IO_RESOURCE_DESCRIPTOR = IVI_ATTR_IO_RESOURCE_DESCRIPTOR
    NIDCPOWER_ATTR_DRIVER_SETUP = IVI_ATTR_DRIVER_SETUP
    NIDCPOWER_ATTR_SOURCE_MODE = NIDCPOWER_ATTR_BASE + 54
    NIDCPOWER_ATTR_OUTPUT_FUNCTION = NIDCPOWER_ATTR_BASE + 8
    NIDCPOWER_ATTR_OUTPUT_ENABLED = IVIDCPWR_ATTR_OUTPUT_ENABLED
    NIDCPOWER_ATTR_OUTPUT_CONNECTED = NIDCPOWER_ATTR_BASE + 60
    NIDCPOWER_ATTR_OUTPUT_RESISTANCE = NIDCPOWER_ATTR_BASE + 61
    NIDCPOWER_ATTR_TRANSIENT_RESPONSE = NIDCPOWER_ATTR_BASE + 62
    NIDCPOWER_ATTR_VOLTAGE_GAIN_BANDWIDTH = NIDCPOWER_ATTR_BASE + 67
    NIDCPOWER_ATTR_VOLTAGE_COMPENSATION_FREQUENCY = NIDCPOWER_ATTR_BASE + 68
    NIDCPOWER_ATTR_VOLTAGE_POLE_ZERO_RATIO = NIDCPOWER_ATTR_BASE + 69
    NIDCPOWER_ATTR_CURRENT_GAIN_BANDWIDTH = NIDCPOWER_ATTR_BASE + 70
    NIDCPOWER_ATTR_CURRENT_COMPENSATION_FREQUENCY = NIDCPOWER_ATTR_BASE + 71
    NIDCPOWER_ATTR_CURRENT_POLE_ZERO_RATIO = NIDCPOWER_ATTR_BASE + 72
    NIDCPOWER_ATTR_VOLTAGE_LEVEL = IVIDCPWR_ATTR_VOLTAGE_LEVEL
    NIDCPOWER_ATTR_CURRENT_LIMIT = IVIDCPWR_ATTR_CURRENT_LIMIT
    NIDCPOWER_ATTR_VOLTAGE_LEVEL_RANGE = NIDCPOWER_ATTR_BASE + 5
    NIDCPOWER_ATTR_CURRENT_LIMIT_RANGE = NIDCPOWER_ATTR_BASE + 4
    NIDCPOWER_ATTR_CURRENT_LIMIT_BEHAVIOR = IVIDCPWR_ATTR_CURRENT_LIMIT_BEHAVIOR
    NIDCPOWER_ATTR_VOLTAGE_LEVEL_AUTORANGE = NIDCPOWER_ATTR_BASE + 15
    NIDCPOWER_ATTR_CURRENT_LIMIT_AUTORANGE = NIDCPOWER_ATTR_BASE + 16
    NIDCPOWER_ATTR_CURRENT_LIMIT_HIGH = NIDCPOWER_ATTR_BASE + 187
    NIDCPOWER_ATTR_CURRENT_LIMIT_LOW = NIDCPOWER_ATTR_BASE + 188
    NIDCPOWER_ATTR_CURRENT_LEVEL = NIDCPOWER_ATTR_BASE + 9
    NIDCPOWER_ATTR_VOLTAGE_LIMIT = NIDCPOWER_ATTR_BASE + 10
    NIDCPOWER_ATTR_CURRENT_LEVEL_RANGE = NIDCPOWER_ATTR_BASE + 11
    NIDCPOWER_ATTR_VOLTAGE_LIMIT_RANGE = NIDCPOWER_ATTR_BASE + 12
    NIDCPOWER_ATTR_CURRENT_LEVEL_AUTORANGE = NIDCPOWER_ATTR_BASE + 17
    NIDCPOWER_ATTR_VOLTAGE_LIMIT_AUTORANGE = NIDCPOWER_ATTR_BASE + 18
    NIDCPOWER_ATTR_VOLTAGE_LIMIT_HIGH = NIDCPOWER_ATTR_BASE + 185
    NIDCPOWER_ATTR_VOLTAGE_LIMIT_LOW = NIDCPOWER_ATTR_BASE + 186
    NIDCPOWER_ATTR_PULSE_VOLTAGE_LEVEL = NIDCPOWER_ATTR_BASE + 80
    NIDCPOWER_ATTR_PULSE_CURRENT_LIMIT = NIDCPOWER_ATTR_BASE + 81
    NIDCPOWER_ATTR_PULSE_BIAS_VOLTAGE_LEVE = NIDCPOWER_ATTR_BASE + 82
    NIDCPOWER_ATTR_PULSE_BIAS_CURRENT_LIMIT = NIDCPOWER_ATTR_BASE + 83
    NIDCPOWER_ATTR_PULSE_VOLTAGE_LEVEL_RANGE = NIDCPOWER_ATTR_BASE + 84
    NIDCPOWER_ATTR_PULSE_CURRENT_LIMIT_RANGE = NIDCPOWER_ATTR_BASE + 85
    NIDCPOWER_ATTR_PULSE_CURRENT_LIMIT_HIGH = NIDCPOWER_ATTR_BASE + 193
    NIDCPOWER_ATTR_PULSE_CURRENT_LIMIT_LOW = NIDCPOWER_ATTR_BASE + 194
    NIDCPOWER_ATTR_PULSE_BIAS_CURRENT_LIMIT_HIGH = NIDCPOWER_ATTR_BASE + 195
    NIDCPOWER_ATTR_PULSE_BIAS_CURRENT_LIMIT_LOW = NIDCPOWER_ATTR_BASE + 196
    NIDCPOWER_ATTR_PULSE_CURRENT_LEVEL = NIDCPOWER_ATTR_BASE + 86
    NIDCPOWER_ATTR_PULSE_VOLTAGE_LIMIT = NIDCPOWER_ATTR_BASE + 87
    NIDCPOWER_ATTR_PULSE_BIAS_CURRENT_LEVEL = NIDCPOWER_ATTR_BASE + 88
    NIDCPOWER_ATTR_PULSE_BIAS_VOLTAGE_LIMIT = NIDCPOWER_ATTR_BASE + 89
    NIDCPOWER_ATTR_PULSE_CURRENT_LEVEL_RANGE = NIDCPOWER_ATTR_BASE + 90
    NIDCPOWER_ATTR_PULSE_VOLTAGE_LIMIT_RANGE = NIDCPOWER_ATTR_BASE + 91
    NIDCPOWER_ATTR_PULSE_VOLTAGE_LIMIT_HIGH = NIDCPOWER_ATTR_BASE + 189
    NIDCPOWER_ATTR_PULSE_VOLTAGE_LIMIT_LOW = NIDCPOWER_ATTR_BASE + 190
    NIDCPOWER_ATTR_PULSE_BIAS_VOLTAGE_LIMIT_HIGH = NIDCPOWER_ATTR_BASE + 191
    NIDCPOWER_ATTR_PULSE_BIAS_VOLTAGE_LIMIT_LOW = NIDCPOWER_ATTR_BASE + 192
    NIDCPOWER_ATTR_SOURCE_DELAY = NIDCPOWER_ATTR_BASE + 51
    NIDCPOWER_ATTR_OVERRANGING_ENABLED = NIDCPOWER_ATTR_BASE + 7
    NIDCPOWER_ATTR_OUTPUT_CAPACITANCE = NIDCPOWER_ATTR_BASE + 14
    NIDCPOWER_ATTR_SEQUENCE_LOOP_COUNT = NIDCPOWER_ATTR_BASE + 25
    NIDCPOWER_ATTR_SEQUENCE_LOOP_COUNT_IS_FINITE = NIDCPOWER_ATTR_BASE + 78
    NIDCPOWER_ATTR_COMPLIANCE_LIMIT_SYMMETRY = NIDCPOWER_ATTR_BASE + 184
    NIDCPOWER_ATTR_SEQUENCE_STEP_DELTA_TIME = NIDCPOWER_ATTR_BASE + 198
    NIDCPOWER_ATTR_SEQUENCE_STEP_DELTA_TIME_ENABLED = NIDCPOWER_ATTR_BASE + 199
    NIDCPOWER_ATTR_ACTUAL_POWER_ALLOCATION = NIDCPOWER_ATTR_BASE + 205
    NIDCPOWER_ATTR_REQUESTED_POWER_ALLOCATION = NIDCPOWER_ATTR_BASE + 206
    NIDCPOWER_ATTR_POWER_ALLOCATION_MODE = NIDCPOWER_ATTR_BASE + 207
    NIDCPOWER_ATTR_PULSE_BIAS_DELAY = NIDCPOWER_ATTR_BASE + 92
    NIDCPOWER_ATTR_PULSE_ON_TIME = NIDCPOWER_ATTR_BASE + 93
    NIDCPOWER_ATTR_PULSE_OFF_TIME = NIDCPOWER_ATTR_BASE + 94
    NIDCPOWER_ATTR_OVP_ENABLED = IVIDCPWR_ATTR_OVP_ENABLED
    NIDCPOWER_ATTR_OVP_LIMIT = IVIDCPWR_ATTR_OVP_LIMIT
    NIDCPOWER_ATTR_SENSE = NIDCPOWER_ATTR_BASE + 13
    NIDCPOWER_ATTR_AUTO_ZERO = NIDCPOWER_ATTR_BASE + 55
    NIDCPOWER_ATTR_APERTURE_TIME = NIDCPOWER_ATTR_BASE + 58
    NIDCPOWER_ATTR_APERTURE_TIME_UNITS = NIDCPOWER_ATTR_BASE + 59
    NIDCPOWER_ATTR_POWER_LINE_FREQUENCY = NIDCPOWER_ATTR_BASE + 20
    NIDCPOWER_ATTR_SAMPLES_TO_AVERAGE = NIDCPOWER_ATTR_BASE + 3
    NIDCPOWER_ATTR_FETCH_BACKLOG = NIDCPOWER_ATTR_BASE + 56
    NIDCPOWER_ATTR_AUTORANGE = NIDCPOWER_ATTR_BASE + 244
    NIDCPOWER_ATTR_MEASURE_WHEN = NIDCPOWER_ATTR_BASE + 57
    NIDCPOWER_ATTR_RESET_AVERAGE_BEFORE_MEASUREMENT = NIDCPOWER_ATTR_BASE + 6
    NIDCPOWER_ATTR_MEASURE_RECORD_LENGTH = NIDCPOWER_ATTR_BASE + 63
    NIDCPOWER_ATTR_MEASURE_RECORD_LENGTH_IS_FINITE = NIDCPOWER_ATTR_BASE + 64
    NIDCPOWER_ATTR_MEASURE_RECORD_DELTA_TIME = NIDCPOWER_ATTR_BASE + 65
    NIDCPOWER_ATTR_DC_NOISE_REJECTION = NIDCPOWER_ATTR_BASE + 66
    NIDCPOWER_ATTR_SELF_CALIBRATION_PERSISTENCE = NIDCPOWER_ATTR_BASE + 73
    NIDCPOWER_ATTR_MEASURE_BUFFER_SIZE = NIDCPOWER_ATTR_BASE + 77
    NIDCPOWER_ATTR_AUTORANGE_BEHAVIOR = NIDCPOWER_ATTR_BASE + 245
    NIDCPOWER_ATTR_AUTORANGE_APERTURE_TIME_MODE = NIDCPOWER_ATTR_BASE + 246
    NIDCPOWER_ATTR_AUTORANGE_MINIMUM_APERTURE_TIME = NIDCPOWER_ATTR_BASE + 247
    NIDCPOWER_ATTR_AUTORANGE_MINIMUM_APERTURE_TIME_UNITS = NIDCPOWER_ATTR_BASE + 248
    NIDCPOWER_ATTR_AUTORANGE_MINIMUM_CURRENT_RANGE = NIDCPOWER_ATTR_BASE + 255
    NIDCPOWER_ATTR_AUTORANGE_MINIMUM_VOLTAGE_RANGE = NIDCPOWER_ATTR_BASE + 256
    NIDCPOWER_ATTR_AUTORANGE_THRESHOLD_MODE = NIDCPOWER_ATTR_BASE + 257
    NIDCPOWER_ATTR_START_TRIGGER_TYPE = NIDCPOWER_ATTR_BASE + 21
    NIDCPOWER_ATTR_DIGITAL_EDGE_START_TRIGGER_EDGE = NIDCPOWER_ATTR_BASE + 22
    NIDCPOWER_ATTR_DIGITAL_EDGE_START_TRIGGER_INPUT_TERMINAL = NIDCPOWER_ATTR_BASE + 23
    NIDCPOWER_ATTR_EXPORTED_START_TRIGGER_OUTPUT_TERMINAL = NIDCPOWER_ATTR_BASE + 24
    NIDCPOWER_ATTR_SOURCE_TRIGGER_TYPE = NIDCPOWER_ATTR_BASE + 30
    NIDCPOWER_ATTR_DIGITAL_EDGE_SOURCE_TRIGGER_EDGE = NIDCPOWER_ATTR_BASE + 31
    NIDCPOWER_ATTR_DIGITAL_EDGE_SOURCE_TRIGGER_INPUT_TERMINAL = NIDCPOWER_ATTR_BASE + 32
    NIDCPOWER_ATTR_EXPORTED_SOURCE_TRIGGER_OUTPUT_TERMINAL = NIDCPOWER_ATTR_BASE + 33
    NIDCPOWER_ATTR_MEASURE_TRIGGER_TYPE = NIDCPOWER_ATTR_BASE + 34
    NIDCPOWER_ATTR_DIGITAL_EDGE_MEASURE_TRIGGER_EDGE = NIDCPOWER_ATTR_BASE + 35
    NIDCPOWER_ATTR_DIGITAL_EDGE_MEASURE_TRIGGER_INPUT_TERMINAL = NIDCPOWER_ATTR_BASE + 36
    NIDCPOWER_ATTR_EXPORTED_MEASURE_TRIGGER_OUTPUT_TERMINAL = NIDCPOWER_ATTR_BASE + 37
    NIDCPOWER_ATTR_SEQUENCE_ADVANCE_TRIGGER_TYPE = NIDCPOWER_ATTR_BASE + 26
    NIDCPOWER_ATTR_DIGITAL_EDGE_SEQUENCE_ADVANCE_TRIGGER_EDGE = NIDCPOWER_ATTR_BASE + 27
    NIDCPOWER_ATTR_DIGITAL_EDGE_SEQUENCE_ADVANCE_TRIGGER_INPUT_TERMINAL = NIDCPOWER_ATTR_BASE + 28
    NIDCPOWER_ATTR_EXPORTED_SEQUENCE_ADVANCE_TRIGGER_OUTPUT_TERMINAL = NIDCPOWER_ATTR_BASE + 29
    NIDCPOWER_ATTR_SOURCE_COMPLETE_EVENT_OUTPUT_TERMINAL = NIDCPOWER_ATTR_BASE + 43
    NIDCPOWER_ATTR_SOURCE_COMPLETE_EVENT_PULSE_POLARITY = NIDCPOWER_ATTR_BASE + 41
    NIDCPOWER_ATTR_SOURCE_COMPLETE_EVENT_PULSE_WIDTH = NIDCPOWER_ATTR_BASE + 42
    NIDCPOWER_ATTR_MEASURE_COMPLETE_EVENT_OUTPUT_TERMINAL = NIDCPOWER_ATTR_BASE + 47
    NIDCPOWER_ATTR_MEASURE_COMPLETE_EVENT_DELAY = NIDCPOWER_ATTR_BASE + 46
    NIDCPOWER_ATTR_MEASURE_COMPLETE_EVENT_PULSE_POLARITY = NIDCPOWER_ATTR_BASE + 44
    NIDCPOWER_ATTR_MEASURE_COMPLETE_EVENT_PULSE_WIDTH = NIDCPOWER_ATTR_BASE + 45
    NIDCPOWER_ATTR_SEQUENCE_ITERATION_COMPLETE_EVENT_OUTPUT_TERMINAL = NIDCPOWER_ATTR_BASE + 40
    NIDCPOWER_ATTR_SEQUENCE_ITERATION_COMPLETE_EVENT_PULSE_POLARITY = NIDCPOWER_ATTR_BASE + 38
    NIDCPOWER_ATTR_SEQUENCE_ITERATION_COMPLETE_EVENT_PULSE_WIDTH = NIDCPOWER_ATTR_BASE + 39
    NIDCPOWER_ATTR_SEQUENCE_ENGINE_DONE_EVENT_OUTPUT_TERMINAL = NIDCPOWER_ATTR_BASE + 50
    NIDCPOWER_ATTR_SEQUENCE_ENGINE_DONE_EVENT_PULSE_POLARITY = NIDCPOWER_ATTR_BASE + 48
    NIDCPOWER_ATTR_SEQUENCE_ENGINE_DONE_EVENT_PULSE_WIDTH = NIDCPOWER_ATTR_BASE + 49
    NIDCPOWER_ATTR_ACTIVE_ADVANCED_SEQUENCE = NIDCPOWER_ATTR_BASE + 74
    NIDCPOWER_ATTR_ACTIVE_ADVANCED_SEQUENCE_STEP = NIDCPOWER_ATTR_BASE + 75
    NIDCPOWER_ATTR_PULSE_TRIGGER_TYPE = NIDCPOWER_ATTR_BASE + 95
    NIDCPOWER_ATTR_DIGITAL_EDGE_PULSE_TRIGGER_EDGE = NIDCPOWER_ATTR_BASE + 96
    NIDCPOWER_ATTR_DIGITAL_EDGE_PULSE_TRIGGER_INPUT_TERMINAL = NIDCPOWER_ATTR_BASE + 97
    NIDCPOWER_ATTR_EXPORTED_PULSE_TRIGGER_OUTPUT_TERMINAL = NIDCPOWER_ATTR_BASE + 98
    NIDCPOWER_ATTR_PULSE_COMPLETE_EVENT_OUTPUT_TERMINAL = NIDCPOWER_ATTR_BASE + 99
    NIDCPOWER_ATTR_PULSE_COMPLETE_EVENT_PULSE_POLARITY = NIDCPOWER_ATTR_BASE + 100
    NIDCPOWER_ATTR_PULSE_COMPLETE_EVENT_PULSE_WIDTH = NIDCPOWER_ATTR_BASE + 101
    NIDCPOWER_ATTR_READY_FOR_PULSE_TRIGGER_EVENT_OUTPUT_TERMINAL = NIDCPOWER_ATTR_BASE + 102
    NIDCPOWER_ATTR_READY_FOR_PULSE_TRIGGER_EVENT_PULSE_POLARITY = NIDCPOWER_ATTR_BASE + 103
    NIDCPOWER_ATTR_READY_FOR_PULSE_TRIGGER_EVENT_PULSE_WIDTH = NIDCPOWER_ATTR_BASE + 104
    NIDCPOWER_ATTR_INTERLOCK_INPUT_OPEN = NIDCPOWER_ATTR_BASE + 105
    NIDCPOWER_ATTR_POWER_SOURCE = NIDCPOWER_ATTR_BASE + 0
    NIDCPOWER_ATTR_POWER_SOURCE_IN_USE = NIDCPOWER_ATTR_BASE + 1
    NIDCPOWER_ATTR_AUXILIARY_POWER_SOURCE_AVAILABLE = NIDCPOWER_ATTR_BASE + 2
End Enum

' Measurement Functions
Public Enum niDCPower_SourceMode
    NIDCPOWER_VAL_SINGLE_POINT = 1020
    NIDCPOWER_VAL_SEQUENCE = 1021
End Enum

Public Enum niDCPower_OutputFunction
    NIDCPOWER_VAL_DC_VOLTAGE = 1006     'Sets the output function to DC voltage.
    NIDCPOWER_VAL_DC_CURRENT = 1007     'Sets the output function to DC current.
    NIDCPOWER_VAL_PULSE_VOLTAGE = 1049  'Sets the output function to pulse voltage.
    NIDCPOWER_VAL_PULSE_CURRENT = 1050  'Sets the output function to pulse current.
End Enum

'/*- Defined values for attributes -*/
'/*-   NIDCPOWER_ATTR_CURRENT_LIMIT_BEHAVIOR -*/
Public Enum niDCPower_CurrentLimitBehavior
    NIDCPOWER_VAL_CURRENT_REGULATE = 0
    NIDCPOWER_VAL_CURRENT_TRIP = 1
End Enum

Public Enum niDCPower_Events
    NIDCPOWER_VAL_SOURCE_COMPLETE_EVENT = 1030              'Waits for the Source Complete event.
    NIDCPOWER_VAL_MEASURE_COMPLETE_EVENT = 1031             'Waits for the Measure Complete event.
    NIDCPOWER_VAL_SEQUENCE_ITERATION_COMPLETE_EVENT = 1032  'Waits for the Sequence Iteration Complete event.
    NIDCPOWER_VAL_SEQUENCE_ENGINE_DONE_EVENT = 1033         'Waits for the Sequence Engine Done event.
    NIDCPOWER_VAL_PULSE_COMPLETE_EVENT = 1051               'Waits for the Pulse Complete event.
    NIDCPOWER_VAL_READY_FOR_PULSE_TRIGGER_EVENT = 1052      'Waits for the Ready for Pulse Trigger event.
End Enum

' niDCPower Factory Method
Public Function niDCPower_CreateSession(resourceName As String, channels As String, Optional Reset As Boolean = True, Optional optionString As String = "") As niDCPower_Session
    Dim session As niDCPower_Session
    
    Set session = New niDCPower_Session
    session.InitSession resourceName, channels, Reset, optionString
    
    Set niDCPower_CreateSession = session
End Function

