Attribute VB_Name = "niRFSA"
Option Explicit

' Attribute IDs
Public Enum niRFSA_AttributeIDs
    NIRFSA_ATTR_CACHE = IVI_ATTR_CACHE
    NIRFSA_ATTR_RANGE_CHECK = IVI_ATTR_RANGE_CHECK
    NIRFSA_ATTR_QUERY_INSTRUMENT_STATUS = IVI_ATTR_QUERY_INSTRUMENT_STATUS
    NIRFSA_ATTR_RECORD_COERCIONS = IVI_ATTR_RECORD_COERCIONS
    NIRFSA_ATTR_SIMULATE = IVI_ATTR_SIMULATE
    NIRFSA_ATTR_INTERCHANGE_CHECK = IVI_ATTR_INTERCHANGE_CHECK
    NIRFSA_ATTR_SPECIFIC_DRIVER_DESCRIPTION = IVI_ATTR_SPECIFIC_DRIVER_DESCRIPTION
    NIRFSA_ATTR_SPECIFIC_DRIVER_PREFIX = IVI_ATTR_SPECIFIC_DRIVER_PREFIX
    NIRFSA_ATTR_SPECIFIC_DRIVER_VENDOR = IVI_ATTR_SPECIFIC_DRIVER_VENDOR
    NIRFSA_ATTR_SPECIFIC_DRIVER_REVISION = IVI_ATTR_SPECIFIC_DRIVER_REVISION
    NIRFSA_ATTR_SUPPORTED_INSTRUMENT_MODELS = IVI_ATTR_SUPPORTED_INSTRUMENT_MODELS
    NIRFSA_ATTR_CHANNEL_COUNT = IVI_ATTR_CHANNEL_COUNT
    NIRFSA_ATTR_INSTRUMENT_MANUFACTURER = IVI_ATTR_INSTRUMENT_MANUFACTURER
    NIRFSA_ATTR_INSTRUMENT_MODEL = IVI_ATTR_INSTRUMENT_MODEL
    NIRFSA_ATTR_INSTRUMENT_FIRMWARE_REVISION = IVI_ATTR_INSTRUMENT_FIRMWARE_REVISION
    NIRFSA_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MAJOR_VERSION = IVI_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MAJOR_VERSION
    NIRFSA_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MINOR_VERSION = IVI_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MINOR_VERSION
    NIRFSA_ATTR_GROUP_CAPABILITIES = IVI_ATTR_GROUP_CAPABILITIES
    NIRFSA_ATTR_MEMORY_SIZE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 85)
    NIRFSA_ATTR_IO_RESOURCE_DESCRIPTOR = IVI_ATTR_IO_RESOURCE_DESCRIPTOR
    NIRFSA_ATTR_LOGICAL_NAME = IVI_ATTR_LOGICAL_NAME
    NIRFSA_ATTR_DRIVER_SETUP = IVI_ATTR_DRIVER_SETUP
    NIRFSA_ATTR_ACQUISITION_TYPE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 1)
    NIRFSA_ATTR_REFERENCE_LEVEL = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 4)
    NIRFSA_ATTR_REFERENCE_LEVEL_HEADROOM = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 309)
    NIRFSA_ATTR_ATTENUATION = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 5)
    NIRFSA_ATTR_MIXER_LEVEL = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 6)
    NIRFSA_ATTR_MIXER_LEVEL_OFFSET = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 127)
    NIRFSA_ATTR_MECHANICAL_ATTENUATION = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 128)
    NIRFSA_ATTR_RF_PREAMP_ENABLED = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 129)
    NIRFSA_ATTR_IF_OUTPUT_POWER_LEVEL = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 130)
    NIRFSA_ATTR_IF_OUTPUT_POWER_LEVEL_OFFSET = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 131)
    NIRFSA_ATTR_RF_ATTENUATION_STEP_SIZE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 155)
    NIRFSA_ATTR_DEVICE_CONFIGURATION_TEMPERATURE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 159)
    NIRFSA_ATTR_IF_ATTENUATION = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 74)
    NIRFSA_ATTR_RF_ATTENUATION_INDEX = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 76)
    NIRFSA_ATTR_RF_ATTENUATION_TABLE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 77)
    NIRFSA_ATTR_IF1_ATTEN_VALUE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 78)
    NIRFSA_ATTR_IF2_ATTEN_VALUE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 79)
    NIRFSA_ATTR_MINIMUM_ACPR = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 142)
    NIRFSA_ATTR_OSP_DATA_SCALING_FACTOR = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 151)
    NIRFSA_ATTR_OVERFLOW_ERROR_REPORTING = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 271)
    NIRFSA_ATTR_STEP_GAIN_ENABLED = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 157)
    NIRFSA_ATTR_AMPLITUDE_SETTLING = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 163)
    NIRFSA_ATTR_DIGITAL_GAIN = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 301)
    NIRFSA_ATTR_CHANNEL_COUPLING = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 149)
    NIRFSA_ATTR_DOWNCONVERTER_PRESELECTOR_ENABLED = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 132)
    NIRFSA_ATTR_INPUT_ISOLATION_ENABLED = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 170)
    NIRFSA_ATTR_RF_PRESELECTOR_FILTER = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 166)
    NIRFSA_ATTR_LOW_FREQUENCY_BYPASS_ENABLED = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 207)
    NIRFSA_ATTR_NOTCH_FILTER_ENABLED = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 167)
    NIRFSA_ATTR_SIGNAL_CONDITIONING_ENABLED = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 160)
    NIRFSA_ATTR_IF_CONDITIONING_DOWN_CONVERSION_ENABLED = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 161)
    NIRFSA_ATTR_IF_FILTER_BANDWIDTH = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 205)
    NIRFSA_ATTR_SELECTED_PORTS = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 297)
    NIRFSA_ATTR_AVAILABLE_PORTS = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 306)
    NIRFSA_ATTR_IQ_CARRIER_FREQUENCY = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 59)
    NIRFSA_ATTR_IQ_RATE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 7)
    NIRFSA_ATTR_NUMBER_OF_SAMPLES_IS_FINITE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 8)
    NIRFSA_ATTR_NUMBER_OF_SAMPLES = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 9)
    NIRFSA_ATTR_NUMBER_OF_RECORDS_IS_FINITE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 10)
    NIRFSA_ATTR_NUMBER_OF_RECORDS = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 11)
    NIRFSA_ATTR_ALLOW_MORE_RECORDS_THAN_MEMORY = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 154)
    NIRFSA_ATTR_CENTER_FREQUENCY = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 2)
    NIRFSA_ATTR_SPECTRUM_SPAN = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 3)
    NIRFSA_ATTR_IF_OUTPUT_FREQUENCY = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 86)
    NIRFSA_ATTR_POWER_SPECTRUM_UNITS = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 12)
    NIRFSA_ATTR_RESOLUTION_BANDWIDTH = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 13)
    NIRFSA_ATTR_RESOLUTION_BANDWIDTH_TYPE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 14)
    NIRFSA_ATTR_SPECTRUM_NUMBER_OF_AVERAGES = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 15)
    NIRFSA_ATTR_SPECTRUM_AVERAGING_MODE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 16)
    NIRFSA_ATTR_FFT_WINDOW_TYPE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 17)
    NIRFSA_ATTR_NUMBER_OF_SPECTRAL_LINES = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 18)
    NIRFSA_ATTR_SPECTRUM_OSP_SAMPLING_RATIO = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 144)
    NIRFSA_ATTR_FFT_WIDTH = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 169)
    NIRFSA_ATTR_SMOOTH_SPECTRUM_ENABLED = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 219)
    NIRFSA_ATTR_REF_CLOCK_SOURCE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 19)
    NIRFSA_ATTR_REF_CLOCK_RATE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 20)
    NIRFSA_ATTR_DIGITIZER_SAMPLE_CLOCK_TIMEBASE_SOURCE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 21)
    NIRFSA_ATTR_DIGITIZER_SAMPLE_CLOCK_TIMEBASE_RATE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 22)
    NIRFSA_ATTR_PXI_CHASSIS_CLK10_SOURCE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 23)
    NIRFSA_ATTR_EXPORTED_REF_CLOCK_OUTPUT_TERMINAL = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 72)
    NIRFSA_ATTR_DIGITIZER_SAMPLE_CLOCK_RATE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 228)
    NIRFSA_ATTR_EXPORTED_DIGITIZER_SAMPLE_CLOCK_OUTPUT_TERMINAL = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 229)
    NIRFSA_ATTR_START_TRIGGER_TYPE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 24)
    NIRFSA_ATTR_DIGITAL_EDGE_START_TRIGGER_SOURCE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 25)
    NIRFSA_ATTR_DIGITAL_EDGE_START_TRIGGER_EDGE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 26)
    NIRFSA_ATTR_EXPORTED_START_TRIGGER_OUTPUT_TERMINAL = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 27)
    NIRFSA_ATTR_START_TRIGGER_TERMINAL_NAME = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 122)
    NIRFSA_ATTR_REF_TRIGGER_TYPE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 28)
    NIRFSA_ATTR_DIGITAL_EDGE_REF_TRIGGER_SOURCE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 29)
    NIRFSA_ATTR_DIGITAL_EDGE_REF_TRIGGER_EDGE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 30)
    NIRFSA_ATTR_REF_TRIGGER_MINIMUM_QUIET_TIME = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 58)
    NIRFSA_ATTR_IQ_POWER_EDGE_REF_TRIGGER_SOURCE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 55)
    NIRFSA_ATTR_IQ_POWER_EDGE_REF_TRIGGER_LEVEL = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 56)
    NIRFSA_ATTR_IQ_POWER_EDGE_REF_TRIGGER_SLOPE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 57)
    NIRFSA_ATTR_EXPORTED_REF_TRIGGER_OUTPUT_TERMINAL = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 32)
    NIRFSA_ATTR_REF_TRIGGER_TERMINAL_NAME = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 123)
    NIRFSA_ATTR_REF_TRIGGER_DELAY = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 60)
    NIRFSA_ATTR_START_TO_REF_TRIGGER_HOLDOFF = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 33)
    NIRFSA_ATTR_REF_TO_REF_TRIGGER_HOLDOFF = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 34)
    NIRFSA_ATTR_REF_TRIGGER_PRETRIGGER_SAMPLES = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 35)
    NIRFSA_ATTR_REF_TRIGGER_OSP_DELAY_ENABLED = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 196)
    NIRFSA_ATTR_ADVANCE_TRIGGER_TYPE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 36)
    NIRFSA_ATTR_DIGITAL_EDGE_ADVANCE_TRIGGER_SOURCE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 37)
    NIRFSA_ATTR_EXPORTED_ADVANCE_TRIGGER_OUTPUT_TERMINAL = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 38)
    NIRFSA_ATTR_ADVANCE_TRIGGER_TERMINAL_NAME = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 124)
    NIRFSA_ATTR_ARM_REF_TRIGGER_TYPE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 39)
    NIRFSA_ATTR_DIGITAL_EDGE_ARM_REF_TRIGGER_SOURCE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 40)
    NIRFSA_ATTR_EXPORTED_READY_FOR_START_EVENT_OUTPUT_TERMINAL = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 41)
    NIRFSA_ATTR_EXPORTED_READY_FOR_ADVANCE_EVENT_OUTPUT_TERMINAL = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 42)
    NIRFSA_ATTR_EXPORTED_READY_FOR_REF_EVENT_OUTPUT_TERMINAL = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 43)
    NIRFSA_ATTR_EXPORTED_END_OF_RECORD_EVENT_OUTPUT_TERMINAL = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 44)
    NIRFSA_ATTR_EXPORTED_DONE_EVENT_OUTPUT_TERMINAL = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 54)
    NIRFSA_ATTR_READY_FOR_START_EVENT_TERMINAL_NAME = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 117)
    NIRFSA_ATTR_READY_FOR_ADVANCE_EVENT_TERMINAL_NAME = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 118)
    NIRFSA_ATTR_READY_FOR_REF_EVENT_TERMINAL_NAME = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 119)
    NIRFSA_ATTR_END_OF_RECORD_EVENT_TERMINAL_NAME = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 120)
    NIRFSA_ATTR_DONE_EVENT_TERMINAL_NAME = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 121)
    NIRFSA_ATTR_USER_SOURCE_PULSE_WIDTH_UNITS = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 321)
    NIRFSA_ATTR_USER_SOURCE_PULSE_WIDTH = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 322)
    NIRFSA_ATTR_FETCH_RELATIVE_TO = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 45)
    NIRFSA_ATTR_FETCH_OFFSET = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 46)
    NIRFSA_ATTR_RECORDS_DONE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 47)
    NIRFSA_ATTR_DATA_TRANSFER_MAXIMUM_BANDWIDTH = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 104)
    NIRFSA_ATTR_DATA_TRANSFER_BLOCK_SIZE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 105)
    NIRFSA_ATTR_PHASE_OFFSET = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 106)
    NIRFSA_ATTR_DIGITAL_IF_EQUALIZATION_ENABLED = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 48)
    NIRFSA_ATTR_FFT_WINDOW_SIZE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 49)
    NIRFSA_ATTR_FFT_SIZE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 50)
    NIRFSA_ATTR_FFT_WINDOW_SHAPE_FACTOR = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 206)
    NIRFSA_ATTR_DEVICE_TEMPERATURE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 51)
    NIRFSA_ATTR_TEMPERATURE_READ_INTERVAL = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 61)
    NIRFSA_ATTR_DOWNCONVERTER_GAIN = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 65)
    NIRFSA_ATTR_NISCOPE_SESSION = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 52)
    NIRFSA_ATTR_RF_CONDITIONING_SESSION = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 200)
    NIRFSA_ATTR_IF_CONDITIONING_SESSION = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 201)
    NIRFSA_ATTR_DIGITIZER_VERTICAL_RANGE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 70)
    NIRFSA_ATTR_ENABLE_FRACTIONAL_RESAMPLING = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 71)
    NIRFSA_ATTR_IF_FILTER = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 75)
    NIRFSA_ATTR_LO_TEMPERATURE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 89)
    NIRFSA_ATTR_DIGITIZER_TEMPERATURE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 90)
    NIRFSA_ATTR_RF_CONDITIONING_TEMPERATURE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 211)
    NIRFSA_ATTR_IF_CONDITIONING_TEMPERATURE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 210)
    NIRFSA_ATTR_FPGA_TEMPERATURE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 254)
    NIRFSA_ATTR_DIGITIZER_DITHER_ENABLED = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 80)
    NIRFSA_ATTR_MECHANICAL_ATTENUATOR_ENABLED = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 81)
    NIRFSA_ATTR_EXTERNAL_GAIN = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 94)
    NIRFSA_ATTR_5665_PRESELECTOR_TUNING_DAC_VALUE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 158)
    NIRFSA_ATTR_ALLOW_OUT_OF_SPECIFICATION_USER_SETTINGS = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 256)
    NIRFSA_ATTR_THERMAL_CORRECTION_TEMPERATURE_RESOLUTION = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 300)
    NIRFSA_ATTR_THERMAL_CORRECTION_HEADROOM_RANGE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 316)
    NIRFSA_ATTR_DOWNCONVERTER_CENTER_FREQUENCY = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 82)
    NIRFSA_ATTR_NIRFSG_SESSION = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 73)
    NIRFSA_ATTR_LO_FREQUENCY = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 68)
    NIRFSA_ATTR_LO_INJECTION_SIDE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 69)
    NIRFSA_ATTR_DOWNCONVERTER_LOOP_BANDWIDTH = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 67)
    NIRFSA_ATTR_FREQUENCY_SETTLING_UNITS = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 87)
    NIRFSA_ATTR_FREQUENCY_SETTLING = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 88)
    NIRFSA_ATTR_LO_EXPORT_ENABLED = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 134)
    NIRFSA_ATTR_LO2_EXPORT_ENABLED = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 235)
    NIRFSA_ATTR_LO_YIG_MAIN_COIL_DRIVE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 135)
    NIRFSA_ATTR_LO_SOURCE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 162)
    NIRFSA_ATTR_RF_OUT_LO_EXPORT_ENABLED = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 298)
    NIRFSA_ATTR_LO_OUT_EXPORT_CONFIGURE_FROM_RFSG = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 299)
    NIRFSA_ATTR_CAL_RF_PATH_SELECTION = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 83)
    NIRFSA_ATTR_CAL_IF_FILTER_SELECTION = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 112)
    NIRFSA_ATTR_CAL_LO_PATH_SELECTION = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 113)
    NIRFSA_ATTR_CAL_IF_ATTENUATION_TABLE_SELECTION = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 141)
    NIRFSA_ATTR_CAL_LO1_ATTENUATION = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 114)
    NIRFSA_ATTR_CAL_LO2_ATTENUATION = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 115)
    NIRFSA_ATTR_CAL_LO3_ATTENUATION = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 116)
    NIRFSA_ATTR_CAL_IF_ATTENUATION_INDEX = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 109)
    NIRFSA_ATTR_CAL_RF_ELECTRONIC_ATTENUATION_INDEX = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 110)
    NIRFSA_ATTR_CAL_RF_MECHANICAL_ATTENUATION_INDEX = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 111)
    NIRFSA_ATTR_CALIBRATION_CORRECTION_THROUGH_FILTER = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 146)
    NIRFSA_ATTR_CALIBRATION_CORRECTION_300_KHZ_FILTER = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 147)
    NIRFSA_ATTR_CALIBRATION_CORRECTION_5_MHZ_FILTER = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 148)
    NIRFSA_ATTR_CALIBRATION_CORRECTION_100_MHZ_FILTER = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 223)
    NIRFSA_ATTR_CALIBRATION_CORRECTION_320_MHZ_FILTER = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 224)
    NIRFSA_ATTR_CALIBRATION_CORRECTION_765_MHZ_FILTER = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 225)
    NIRFSA_ATTR_CAL_DIGITIZER_ID = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 226)
    NIRFSA_ATTR_CAL_RF_LOWBAND_SIGNAL_CONDITIONING_PATH_SELECTION = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 215)
    NIRFSA_ATTR_RF_HIGH_PASS_FILTERING = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 220)
    NIRFSA_ATTR_CAL_IF_ATTENUATION_TABLE_SIZE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 216)
    NIRFSA_ATTR_SERIAL_NUMBER = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 53)
    NIRFSA_ATTR_MODULE_REVISION = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 91)
    NIRFSA_ATTR_MODULE_POWER_CONSUMPTION = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 255)
    NIRFSA_ATTR_SIGNAL_BANDWIDTH = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 267)
    NIRFSA_ATTR_DEVICE_INSTANTANEOUS_BANDWIDTH = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 125)
    NIRFSA_ATTR_PRESELECTOR_PRESENT = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 136)
    NIRFSA_ATTR_RF_PREAMP_PRESENT = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 137)
    NIRFSA_ATTR_MAX_DEVICE_INSTANTANEOUS_BANDWIDTH = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 236)
    NIRFSA_ATTR_MAX_IQ_RATE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 237)
    NIRFSA_ATTR_ACTIVE_CONFIGURATION_LIST = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 92)
    NIRFSA_ATTR_ACTIVE_CONFIGURATION_LIST_STEP = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 93)
    NIRFSA_ATTR_DIGITAL_EDGE_CONFIGURATION_LIST_STEP_TRIGGER_SOURCE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 95)
    NIRFSA_ATTR_CONFIGURATION_LIST_STEP_IN_PROGRESS = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 126)
    NIRFSA_ATTR_DDC_REF_TRIGGER_OVERRIDE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 164)
    NIRFSA_ATTR_MINIMUM_RECONFIG_TIME = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 165)
    NIRFSA_ATTR_CONTIGUOUS_MULTIRECORD = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 172)
    NIRFSA_ATTR_TIMER_START_SOURCE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 173)
    NIRFSA_ATTR_START_TRIGGER_DELAY = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 175)
    NIRFSA_ATTR_TIMER_EVENT_INTERVAL = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 96)
    NIRFSA_ATTR_P2P_ENABLED = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 97)
    NIRFSA_ATTR_P2P_FIFO_ENDPOINT_COUNT = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 98)
    NIRFSA_ATTR_P2P_SAMPLES_TRANSFERRED = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 99)
    NIRFSA_ATTR_P2P_SAMPLES_AVAILABLE_IN_ENDPOINT = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 100)
    NIRFSA_ATTR_P2P_MOST_SAMPLES_AVAILABLE_IN_ENDPOINT = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 101)
    NIRFSA_ATTR_P2P_ENDPOINT_SIZE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 102)
    NIRFSA_ATTR_P2P_ENDPOINT_OVERFLOW = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 103)
    NIRFSA_ATTR_P2P_ONBOARD_MEMORY_ENABLED = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 107)
    NIRFSA_ATTR_DOWNCONVERTER_CAL_TONE_MODE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 139)
    NIRFSA_ATTR_DOWNCONVERTER_CAL_TONE_FREQUENCY = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 140)
    NIRFSA_ATTR_RF_CONDITIONING_CAL_TONE_MODE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 208)
    NIRFSA_ATTR_RF_CONDITIONING_CAL_TONE_FREQUENCY = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 209)
    NIRFSA_ATTR_CAL_TONE_STEP_ATTENUATION = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 168)
    NIRFSA_ATTR_CAL_TONE_POWER_REFERRED_TO_RF_IN = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 174)
    NIRFSA_ATTR_NOISE_SOURCE_POWER_ENABLED = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 222)
    NIRFSA_ATTR_INPUT_PORT = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 180)
    NIRFSA_ATTR_LO_IN_POWER = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 186)
    NIRFSA_ATTR_LO_OUT_POWER = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 246)
    NIRFSA_ATTR_LO_PLL_FRACTIONAL_MODE_ENABLED = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 187)
    NIRFSA_ATTR_LO_FREQUENCY_STEP_SIZE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 188)
    NIRFSA_ATTR_LO_VCO_FREQUENCY_STEP_SIZE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 312)
    NIRFSA_ATTR_IQ_IN_PORT_CARRIER_FREQUENCY = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 181)
    NIRFSA_ATTR_IQ_IN_PORT_TERMINAL_CONFIGURATION = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 182)
    NIRFSA_ATTR_IQ_IN_PORT_VERTICAL_RANGE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 183)
    NIRFSA_ATTR_IQ_IN_PORT_TEMPERATURE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 204)
    NIRFSA_ATTR_COMMON_MODE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 269)
    NIRFSA_ATTR_SYNC_START_TRIGGER_MASTER = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 176)
    NIRFSA_ATTR_SYNC_START_TRIGGER_DIST_LINE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 177)
    NIRFSA_ATTR_SYNC_REF_TRIGGER_MASTER = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 178)
    NIRFSA_ATTR_SYNC_REF_TRIGGER_DIST_LINE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 179)
    NIRFSA_ATTR_SYNC_REF_TRIGGER_DELAY_ENABLED = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 189)
    NIRFSA_ATTR_SYNC_ADVANCE_TRIGGER_MASTER = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 184)
    NIRFSA_ATTR_SYNC_ADVANCE_TRIGGER_DIST_LINE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 185)
    NIRFSA_ATTR_SYNC_SAMPLE_CLOCK_MASTER = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 217)
    NIRFSA_ATTR_SYNC_SAMPLE_CLOCK_DIST_LINE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 218)
    NIRFSA_ATTR_IQ_ANALOG_EDGE_REF_TRIGGER_SOURCE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 192)
    NIRFSA_ATTR_IQ_ANALOG_EDGE_REF_TRIGGER_SLOPE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 193)
    NIRFSA_ATTR_IQ_ANALOG_EDGE_REF_TRIGGER_LEVEL = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 194)
    NIRFSA_ATTR_IQ_ANALOG_EDGE_REF_TRIGGER_HYSTERESIS = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 195)
    NIRFSA_ATTR_DECIMATION_DELAY = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 191)
    NIRFSA_ATTR_ABSOLUTE_DELAY = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 266)
    NIRFSA_ATTR_DOWNCONVERTER_FREQUENCY_OFFSET_MODE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 305)
    NIRFSA_ATTR_DOWNCONVERTER_FREQUENCY_OFFSET = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 203)
    NIRFSA_ATTR_FPGA_BITFILE_PATH = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 221)
    NIRFSA_ATTR_FPGA_TARGET_NAME = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 233)
    NIRFSA_ATTR_SUBSPAN_OVERLAP = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 234)
    NIRFSA_ATTR_HOST_DMA_BUFFER_SIZE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 285)
    NIRFSA_ATTR_DEEMBEDDING_TYPE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 307)
    NIRFSA_ATTR_DEEMBEDDING_SELECTED_TABLE = (IVI_SPECIFIC_PUBLIC_ATTR_BASE + 308)
End Enum

'- NIRFSA_ATTR_ACQUISITION_TYPE Values -
Public Enum niRFSA_AcquisitionType
    NIRFSA_VAL_IQ = 100
    NIRFSA_VAL_SPECTRUM = 101
End Enum

' - Values for SELF CAL steps -
Public Enum niRFSA_SelfCalSteps
    NIRFSA_VAL_SELF_CAL_OMIT_NONE = &H0
    NIRFSA_VAL_SELF_CAL_PRESELECTOR_ALIGNMENT = &H1
    NIRFSA_VAL_SELF_CAL_GAIN_REFERENCE = &H2
    NIRFSA_VAL_SELF_CAL_IF_FLATNESS = &H4
    NIRFSA_VAL_SELF_CAL_DIGITIZER_SELF_CAL = &H8
    NIRFSA_VAL_SELF_CAL_LO_SELF_CAL = &H10
    NIRFSA_VAL_SELF_CAL_AMPLITUDE_ACCURACY = &H20
    NIRFSA_VAL_SELF_CAL_RESIDUAL_LO_POWER = &H40
    NIRFSA_VAL_SELF_CAL_IMAGE_SUPPRESSION = &H80
    NIRFSA_VAL_SELF_CAL_SYNTHESIZER_ALIGNMENT = &H100
    NIRFSA_VAL_SELF_CAL_DC_OFFSET = &H200
End Enum

Type niRFSA_wfmInfo
   absoluteInitialX As Double
   relativeInitialX As Double
   xIncrement As Double
   actualSamples As LongLong
   offset As Double
   gain As Double
   reserved1 As Double
   reserved2 As Double
End Type

' niRFSA Factory Method
Public Function niRFSA_CreateSession( _
        resourceName As String, _
        Optional IDQuery As Boolean = True, _
        Optional Reset As Boolean = True, _
        Optional optionString As String = "" _
    ) As niRFSA_Session
    
    Dim session As niRFSA_Session
    
    Set session = New niRFSA_Session
    session.InitSession resourceName, IDQuery, Reset, optionString
    
    Set niRFSA_CreateSession = session
End Function
