Attribute VB_Name = "niDMM"
Option Explicit

Private Const NIDMM_ATTR_BASE = IVI_SPECIFIC_PUBLIC_ATTR_BASE
Private Const NIDMM_ATTR_PRIVATE_BASE = IVI_SPECIFIC_PRIVATE_ATTR_BASE

Private Enum IviDMM_AttributeIDs
    IVIDMM_ATTR_CACHE = IVI_ATTR_CACHE
    IVIDMM_ATTR_RANGE_CHECK = IVI_ATTR_RANGE_CHECK
    IVIDMM_ATTR_QUERY_INSTRUMENT_STATUS = IVI_ATTR_QUERY_INSTRUMENT_STATUS
    IVIDMM_ATTR_RECORD_COERCIONS = IVI_ATTR_RECORD_COERCIONS
    IVIDMM_ATTR_SIMULATE = IVI_ATTR_SIMULATE
    IVIDMM_ATTR_INTERCHANGE_CHECK = IVI_ATTR_INTERCHANGE_CHECK
    IVIDMM_ATTR_SPY = IVI_ATTR_SPY
    IVIDMM_ATTR_USE_SPECIFIC_SIMULATION = IVI_ATTR_USE_SPECIFIC_SIMULATION
    IVIDMM_ATTR_GROUP_CAPABILITIES = IVI_ATTR_GROUP_CAPABILITIES
    IVIDMM_ATTR_FUNCTION_CAPABILITIES = IVI_ATTR_FUNCTION_CAPABILITIES
    IVIDMM_ATTR_CLASS_DRIVER_PREFIX = IVI_ATTR_CLASS_DRIVER_PREFIX
    IVIDMM_ATTR_CLASS_DRIVER_VENDOR = IVI_ATTR_CLASS_DRIVER_VENDOR
    IVIDMM_ATTR_CLASS_DRIVER_DESCRIPTION = IVI_ATTR_CLASS_DRIVER_DESCRIPTION
    IVIDMM_ATTR_CLASS_DRIVER_CLASS_SPEC_MAJOR_VERSION = IVI_ATTR_CLASS_DRIVER_CLASS_SPEC_MAJOR_VERSION
    IVIDMM_ATTR_CLASS_DRIVER_CLASS_SPEC_MINOR_VERSION = IVI_ATTR_CLASS_DRIVER_CLASS_SPEC_MINOR_VERSION
    IVIDMM_ATTR_SPECIFIC_DRIVER_PREFIX = IVI_ATTR_SPECIFIC_DRIVER_PREFIX
    IVIDMM_ATTR_SPECIFIC_DRIVER_LOCATOR = IVI_ATTR_SPECIFIC_DRIVER_LOCATOR
    IVIDMM_ATTR_IO_RESOURCE_DESCRIPTOR = IVI_ATTR_IO_RESOURCE_DESCRIPTOR
    IVIDMM_ATTR_LOGICAL_NAME = IVI_ATTR_LOGICAL_NAME
    IVIDMM_ATTR_SPECIFIC_DRIVER_VENDOR = IVI_ATTR_SPECIFIC_DRIVER_VENDOR
    IVIDMM_ATTR_SPECIFIC_DRIVER_DESCRIPTION = IVI_ATTR_SPECIFIC_DRIVER_DESCRIPTION
    IVIDMM_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MAJOR_VERSION = IVI_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MAJOR_VERSION
    IVIDMM_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MINOR_VERSION = IVI_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MINOR_VERSION
    IVIDMM_ATTR_INSTRUMENT_FIRMWARE_REVISION = IVI_ATTR_INSTRUMENT_FIRMWARE_REVISION
    IVIDMM_ATTR_INSTRUMENT_MANUFACTURER = IVI_ATTR_INSTRUMENT_MANUFACTURER
    IVIDMM_ATTR_INSTRUMENT_MODEL = IVI_ATTR_INSTRUMENT_MODEL
    IVIDMM_ATTR_SUPPORTED_INSTRUMENT_MODELS = IVI_ATTR_SUPPORTED_INSTRUMENT_MODELS
    IVIDMM_ATTR_CLASS_DRIVER_REVISION = IVI_ATTR_CLASS_DRIVER_REVISION
    IVIDMM_ATTR_SPECIFIC_DRIVER_REVISION = IVI_ATTR_SPECIFIC_DRIVER_REVISION
    IVIDMM_ATTR_DRIVER_SETUP = IVI_ATTR_DRIVER_SETUP
    IVIDMM_ATTR_FUNCTION = (IVI_CLASS_PUBLIC_ATTR_BASE + 1)
    IVIDMM_ATTR_RANGE = (IVI_CLASS_PUBLIC_ATTR_BASE + 2)
    IVIDMM_ATTR_RESOLUTION_ABSOLUTE = (IVI_CLASS_PUBLIC_ATTR_BASE + 8)
    IVIDMM_ATTR_TRIGGER_SOURCE = (IVI_CLASS_PUBLIC_ATTR_BASE + 4)
    IVIDMM_ATTR_TRIGGER_DELAY = (IVI_CLASS_PUBLIC_ATTR_BASE + 5)
    IVIDMM_ATTR_AC_MIN_FREQ = (IVI_CLASS_PUBLIC_ATTR_BASE + 6)
    IVIDMM_ATTR_AC_MAX_FREQ = (IVI_CLASS_PUBLIC_ATTR_BASE + 7)
    IVIDMM_ATTR_FREQ_VOLTAGE_RANGE = (IVI_CLASS_PUBLIC_ATTR_BASE + 101)
    IVIDMM_ATTR_TEMP_TRANSDUCER_TYPE = (IVI_CLASS_PUBLIC_ATTR_BASE + 201)
    IVIDMM_ATTR_TEMP_TC_TYPE = (IVI_CLASS_PUBLIC_ATTR_BASE + 231)
    IVIDMM_ATTR_TEMP_TC_REF_JUNC_TYPE = (IVI_CLASS_PUBLIC_ATTR_BASE + 232)
    IVIDMM_ATTR_TEMP_TC_FIXED_REF_JUNC = (IVI_CLASS_PUBLIC_ATTR_BASE + 233)
    IVIDMM_ATTR_TEMP_RTD_ALPHA = (IVI_CLASS_PUBLIC_ATTR_BASE + 241)
    IVIDMM_ATTR_TEMP_RTD_RES = (IVI_CLASS_PUBLIC_ATTR_BASE + 242)
    IVIDMM_ATTR_TEMP_THERMISTOR_RES = (IVI_CLASS_PUBLIC_ATTR_BASE + 251)
    IVIDMM_ATTR_SAMPLE_COUNT = (IVI_CLASS_PUBLIC_ATTR_BASE + 301)
    IVIDMM_ATTR_SAMPLE_TRIGGER = (IVI_CLASS_PUBLIC_ATTR_BASE + 302)
    IVIDMM_ATTR_SAMPLE_INTERVAL = (IVI_CLASS_PUBLIC_ATTR_BASE + 303)
    IVIDMM_ATTR_TRIGGER_COUNT = (IVI_CLASS_PUBLIC_ATTR_BASE + 304)
    IVIDMM_ATTR_MEAS_COMPLETE_DEST = (IVI_CLASS_PUBLIC_ATTR_BASE + 305)
    IVIDMM_ATTR_TRIGGER_SLOPE = (IVI_CLASS_PUBLIC_ATTR_BASE + 334)
    IVIDMM_ATTR_APERTURE_TIME = (IVI_CLASS_PUBLIC_ATTR_BASE + 321)
    IVIDMM_ATTR_APERTURE_TIME_UNITS = (IVI_CLASS_PUBLIC_ATTR_BASE + 322)
    IVIDMM_ATTR_AUTO_RANGE_VALUE = (IVI_CLASS_PUBLIC_ATTR_BASE + 331)
    IVIDMM_ATTR_AUTO_ZERO = (IVI_CLASS_PUBLIC_ATTR_BASE + 332)
    IVIDMM_ATTR_POWERLINE_FREQ = (IVI_CLASS_PUBLIC_ATTR_BASE + 333)
End Enum

' Attribute IDs
Public Enum niDMM_AttributeIDs
   NIDMM_ATTR_RANGE_CHECK = IVI_ATTR_RANGE_CHECK
   NIDMM_ATTR_QUERY_INSTRUMENT_STATUS = IVI_ATTR_QUERY_INSTRUMENT_STATUS
   NIDMM_ATTR_CACHE = IVI_ATTR_CACHE
   NIDMM_ATTR_SIMULATE = IVI_ATTR_SIMULATE
   NIDMM_ATTR_RECORD_COERCIONS = IVI_ATTR_RECORD_COERCIONS
   NIDMM_ATTR_INTERCHANGE_CHECK = IVI_ATTR_INTERCHANGE_CHECK
   NIDMM_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MAJOR_VERSION = IVI_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MAJOR_VERSION
   NIDMM_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MINOR_VERSION = IVI_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MINOR_VERSION
   NIDMM_ATTR_SPECIFIC_DRIVER_DESCRIPTION = IVI_ATTR_SPECIFIC_DRIVER_DESCRIPTION
   NIDMM_ATTR_SPECIFIC_DRIVER_PREFIX = IVI_ATTR_SPECIFIC_DRIVER_PREFIX
   NIDMM_ATTR_SPECIFIC_DRIVER_VENDOR = IVI_ATTR_SPECIFIC_DRIVER_VENDOR
   NIDMM_ATTR_SPECIFIC_DRIVER_REVISION = IVI_ATTR_SPECIFIC_DRIVER_REVISION
   NIDMM_ATTR_CLASS_DRIVER_CLASS_SPEC_MAJOR_VERSION = IVI_ATTR_CLASS_DRIVER_CLASS_SPEC_MAJOR_VERSION
   NIDMM_ATTR_CLASS_DRIVER_CLASS_SPEC_MINOR_VERSION = IVI_ATTR_CLASS_DRIVER_CLASS_SPEC_MINOR_VERSION
   NIDMM_ATTR_CHANNEL_COUNT = IVI_ATTR_CHANNEL_COUNT
   NIDMM_ATTR_SUPPORTED_INSTRUMENT_MODELS = IVI_ATTR_SUPPORTED_INSTRUMENT_MODELS
   NIDMM_ATTR_GROUP_CAPABILITIES = IVI_ATTR_GROUP_CAPABILITIES
   NIDMM_ATTR_INSTRUMENT_MANUFACTURER = IVI_ATTR_INSTRUMENT_MANUFACTURER
   NIDMM_ATTR_INSTRUMENT_MODEL = IVI_ATTR_INSTRUMENT_MODEL
   NIDMM_ATTR_INSTRUMENT_FIRMWARE_REVISION = IVI_ATTR_INSTRUMENT_FIRMWARE_REVISION
   NIDMM_ATTR_LOGICAL_NAME = IVI_ATTR_LOGICAL_NAME
   NIDMM_ATTR_IO_RESOURCE_DESCRIPTOR = IVI_ATTR_IO_RESOURCE_DESCRIPTOR
   NIDMM_ATTR_DRIVER_SETUP = IVI_ATTR_DRIVER_SETUP
   NIDMM_ATTR_IO_SESSION = IVI_ATTR_SYSTEM_IO_SESSION
   NIDMM_ATTR_FUNCTION = IVIDMM_ATTR_FUNCTION
   NIDMM_ATTR_RANGE = IVIDMM_ATTR_RANGE
   NIDMM_ATTR_RESOLUTION_ABSOLUTE = IVIDMM_ATTR_RESOLUTION_ABSOLUTE
   NIDMM_ATTR_RESOLUTION_DIGITS = (IVI_CLASS_PUBLIC_ATTR_BASE + 3)
   NIDMM_ATTR_TRIGGER_DELAY = IVIDMM_ATTR_TRIGGER_DELAY
   NIDMM_ATTR_TRIGGER_SOURCE = IVIDMM_ATTR_TRIGGER_SOURCE
   NIDMM_ATTR_AC_MAX_FREQ = IVIDMM_ATTR_AC_MAX_FREQ
   NIDMM_ATTR_AC_MIN_FREQ = IVIDMM_ATTR_AC_MIN_FREQ
   NIDMM_ATTR_FREQ_VOLTAGE_RANGE = IVIDMM_ATTR_FREQ_VOLTAGE_RANGE
   NIDMM_ATTR_MEAS_COMPLETE_DEST = IVIDMM_ATTR_MEAS_COMPLETE_DEST
   NIDMM_ATTR_SAMPLE_COUNT = IVIDMM_ATTR_SAMPLE_COUNT
   NIDMM_ATTR_SAMPLE_INTERVAL = IVIDMM_ATTR_SAMPLE_INTERVAL
   NIDMM_ATTR_SAMPLE_TRIGGER = IVIDMM_ATTR_SAMPLE_TRIGGER
   NIDMM_ATTR_TRIGGER_COUNT = IVIDMM_ATTR_TRIGGER_COUNT
   NIDMM_ATTR_APERTURE_TIME = IVIDMM_ATTR_APERTURE_TIME
   NIDMM_ATTR_APERTURE_TIME_UNITS = IVIDMM_ATTR_APERTURE_TIME_UNITS
   NIDMM_ATTR_AUTO_RANGE_VALUE = IVIDMM_ATTR_AUTO_RANGE_VALUE
   NIDMM_ATTR_AUTO_ZERO = IVIDMM_ATTR_AUTO_ZERO
   NIDMM_ATTR_POWERLINE_FREQ = IVIDMM_ATTR_POWERLINE_FREQ
   NIDMM_ATTR_TRIGGER_SLOPE = IVIDMM_ATTR_TRIGGER_SLOPE
   NIDMM_ATTR_SAMPLE_TRIGGER_SLOPE = (NIDMM_ATTR_BASE + 10)
   NIDMM_ATTR_MEAS_DEST_SLOPE = (NIDMM_ATTR_BASE + 2)
   NIDMM_ATTR_ADC_CALIBRATION = (NIDMM_ATTR_BASE + 22)
   NIDMM_ATTR_OFFSET_COMP_OHMS = (NIDMM_ATTR_BASE + 23)
   NIDMM_ATTR_NUMBER_OF_AVERAGES = (NIDMM_ATTR_BASE + 32)
   NIDMM_ATTR_CURRENT_SOURCE = (NIDMM_ATTR_BASE + 25)
   NIDMM_ATTR_DC_NOISE_REJECTION = (NIDMM_ATTR_BASE + 26)
   NIDMM_ATTR_SETTLE_TIME = (NIDMM_ATTR_BASE + 28)
   NIDMM_ATTR_INPUT_RESISTANCE = (NIDMM_ATTR_BASE + 29)
   NIDMM_ATTR_LATENCY = (NIDMM_ATTR_BASE + 34)
   NIDMM_ATTR_BUFFER_SIZE = (NIDMM_ATTR_BASE + 37)
   NIDMM_ATTR_SHUNT_VALUE = (NIDMM_ATTR_BASE + 3)
   NIDMM_ATTR_OPERATION_MODE = (NIDMM_ATTR_BASE + 14)
   NIDMM_ATTR_WAVEFORM_RATE = (NIDMM_ATTR_BASE + 18)
   NIDMM_ATTR_WAVEFORM_POINTS = (NIDMM_ATTR_BASE + 19)
   NIDMM_ATTR_WAVEFORM_COUPLING = (NIDMM_ATTR_BASE + 27)
   NIDMM_ATTR_FREQ_VOLTAGE_AUTO_RANGE_VALUE = (NIDMM_ATTR_BASE + 44)
   NIDMM_ATTR_CABLE_COMP_TYPE = (NIDMM_ATTR_BASE + 45)
   NIDMM_ATTR_SHORT_CABLE_COMP_REACTANCE = (NIDMM_ATTR_BASE + 46)
   NIDMM_ATTR_SHORT_CABLE_COMP_RESISTANCE = (NIDMM_ATTR_BASE + 47)
   NIDMM_ATTR_OPEN_CABLE_COMP_SUSCEPTANCE = (NIDMM_ATTR_BASE + 48)
   NIDMM_ATTR_OPEN_CABLE_COMP_CONDUCTANCE = (NIDMM_ATTR_BASE + 49)
   NIDMM_ATTR_LC_CALCULATION_MODEL = (NIDMM_ATTR_BASE + 52)
   NIDMM_ATTR_DC_BIAS = (NIDMM_ATTR_BASE + 53)
   NIDMM_ATTR_LC_NUMBER_MEAS_TO_AVERAGE = (NIDMM_ATTR_BASE + 55)
   NIDMM_ATTR_SERIAL_NUMBER = (NIDMM_ATTR_BASE + 54)
   NIDMM_ATTR_CONFIG_PRODUCT_NUMBER = (NIDMM_ATTR_BASE + 61)
   NIDMM_ATTR_TEMP_TRANSDUCER_TYPE = IVIDMM_ATTR_TEMP_TRANSDUCER_TYPE
   NIDMM_ATTR_TEMP_TC_REF_JUNC_TYPE = IVIDMM_ATTR_TEMP_TC_REF_JUNC_TYPE
   NIDMM_ATTR_TEMP_TC_TYPE = IVIDMM_ATTR_TEMP_TC_TYPE
   NIDMM_ATTR_TEMP_TC_FIXED_REF_JUNC = IVIDMM_ATTR_TEMP_TC_FIXED_REF_JUNC
   NIDMM_ATTR_TEMP_RTD_TYPE = (NIDMM_ATTR_BASE + 120)
   NIDMM_ATTR_TEMP_RTD_RES = IVIDMM_ATTR_TEMP_RTD_RES
   NIDMM_ATTR_TEMP_RTD_A = (NIDMM_ATTR_BASE + 121)
   NIDMM_ATTR_TEMP_RTD_B = (NIDMM_ATTR_BASE + 122)
   NIDMM_ATTR_TEMP_RTD_C = (NIDMM_ATTR_BASE + 123)
   NIDMM_ATTR_TEMP_THERMISTOR_TYPE = (NIDMM_ATTR_BASE + 124)
   NIDMM_ATTR_TEMP_THERMISTOR_A = (NIDMM_ATTR_BASE + 125)
   NIDMM_ATTR_TEMP_THERMISTOR_B = (NIDMM_ATTR_BASE + 126)
   NIDMM_ATTR_TEMP_THERMISTOR_C = (NIDMM_ATTR_BASE + 127)
End Enum

' Measurement Functions
Public Enum niDMM_MeasurementFunction
    NIDMM_VAL_DC_VOLTS = 1                'DC Voltage                     All
    NIDMM_VAL_AC_VOLTS = 2                'AC Voltage with AC Coupling    All
    NIDMM_VAL_DC_CURRENT = 3              'DC Current                     All
    NIDMM_VAL_AC_CURRENT = 4              'AC Current                     All
    NIDMM_VAL_2_WIRE_RES = 5              '2-Wire Resistance              All
    NIDMM_VAL_4_WIRE_RES = 101            '4-Wire Resistance              NI 4060, NI 4065, NI 4070/4071/4072, NI 4080/4081/4082
    NIDMM_VAL_FREQ = 104                  'Frequency                      NI 4070/4071/4072 and NI 4080/4081/4082
    NIDMM_VAL_PERIOD = 105                'Period                         NI 4070/4071/4072 and NI 4080/4081/4082
    NIDMM_VAL_TEMPERATURE = 108           'Temperature
    NIDMM_VAL_AC_VOLTS_DC_COUPLED = 1001  'AC Voltage with DC Coupling    NI 4070/4071/4072 and NI 4080/4081/4082
    NIDMM_VAL_DIODE = 1002                'Diode                          All
    NIDMM_VAL_WAVEFORM_VOLTAGE = 1003     'Waveform Voltage               NI 4070/4071/4072 and NI 4080/4081/4082
    NIDMM_VAL_WAVEFORM_CURRENT = 1004     'Waveform Current               NI 4070/4071/4072 and NI 4080/4081/4082
    NIDMM_VAL_CAPACITANCE = 1005          'Capacitance                    NI 4072 and NI 4082
    NIDMM_VAL_INDUCTANCE = 1006           'Inductance                     NI 4072 and NI 4082
End Enum

' Auto Range Values
Public Const NIDMM_VAL_AUTO_RANGE_ON As Double = -1#
Public Const NIDMM_VAL_AUTO_RANGE_OFF As Double = -2#
Public Const NIDMM_VAL_AUTO_RANGE_ONCE As Double = -3#

' Powerline Frequencies
Public Const NIDMM_VAL_50_HERTZ As Double = 50#
Public Const NIDMM_VAL_60_HERTZ As Double = 60#

' Auto Time Limit
Public Const NIDMM_VAL_TIME_LIMIT_AUTO As Double = -1

' niDMM Factory Method
Public Function niDMM_CreateSession(resourceName As String, Optional IDQuery As Boolean = True, Optional Reset As Boolean = True) As niDMM_Session
    Dim session As niDMM_Session
    
    Set session = New niDMM_Session
    session.InitSession resourceName, IDQuery, Reset
    
    Set niDMM_CreateSession = session
End Function

